// Generates small TS modules the site needs at build time:
//  - src/generated/ui-icons.ts : TypeIcon Core line/filled icons used by the site UI (dogfooding)
//  - src/generated/synonyms.ts : website search synonym groups (assets/registry/synonyms.json)
// Run automatically by predev/prebuild.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");
const out = path.resolve(here, "../src/generated");
mkdirSync(out, { recursive: true });

function inner(svg) {
  const m = svg.match(/^<svg([^>]*)>([\s\S]*)<\/svg>\s*$/);
  const attrs = Object.fromEntries([...m[1].matchAll(/([\w:-]+)="([^"]*)"/g)].map((a) => [a[1], a[2]]));
  return { attrs, body: m[2].replace(/\n\s*/g, "").trim() };
}
const icons = {};
for (const style of ["line", "filled"]) {
  const dir = path.join(root, "assets/core/svg", style);
  for (const f of readdirSync(dir).sort()) {
    const { attrs, body } = inner(readFileSync(path.join(dir, f), "utf8"));
    const keep = Object.fromEntries(Object.entries(attrs).filter(([k]) => !["xmlns", "width", "height"].includes(k)));
    icons[`${style}/${f.replace(/\.svg$/, "")}`] = { attrs: keep, body };
  }
}
writeFileSync(
  path.join(out, "ui-icons.ts"),
  "// Generated by scripts/generate-assets.mjs from assets/core/svg. Do not edit.\n" +
    "export const uiIcons: Record<string, { attrs: Record<string, string>; body: string }> = " +
    JSON.stringify(icons) + ";\nexport type UiIconName = keyof typeof uiIcons;\n",
);
const syn = JSON.parse(readFileSync(path.join(root, "assets/registry/synonyms.json"), "utf8"));
writeFileSync(
  path.join(out, "synonyms.ts"),
  "// Generated from assets/registry/synonyms.json. Website search only; never compiled into fonts.\n" +
    "export const synonymGroups: string[][] = " + JSON.stringify(syn.groups) + ";\n",
);
console.log(`generated ${Object.keys(icons).length} UI icons, ${syn.groups.length} synonym groups`);
