/**
 * Apply SQL migrations from db/migrations (generated by drizzle-kit, reviewed, committed).
 * Extensions are created first because generated indexes depend on pg_trgm.
 * Usage: DATABASE_URL=... pnpm db:migrate
 */
import path from "node:path";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is required");
  const pool = new Pool({ connectionString: url, max: 1 });
  try {
    await pool.query("CREATE EXTENSION IF NOT EXISTS pg_trgm");
    await pool.query("CREATE SCHEMA IF NOT EXISTS loadtest");
    await migrate(drizzle(pool), { migrationsFolder: path.resolve(__dirname, "../../../db/migrations") });
    console.log("migrations applied");
  } finally {
    await pool.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
