/**
 * TypeIcon database schema (catalog, releases, fonts, kits, jobs, audit).
 * Auth tables live in ./auth-schema.ts (generated by the Better Auth CLI).
 *
 * Identifiers: catalog rows use stable UUIDv5 ids computed by the import pipeline, so a
 * variant keeps its id across rebuilds. Glyph ids are never stored as identifiers.
 * Codepoints are integers (supplementary private-use planes need > 16 bits).
 */
import { sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  customType,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { user } from "./auth-schema";

const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });
const now = () => timestamp({ withTimezone: true }).notNull().defaultNow();

// ------------------------------------------------------------------ licenses & sources

export const licenses = pgTable("licenses", {
  id: text().primaryKey(), // SPDX id or LicenseRef-*
  name: text().notNull(),
  url: text(),
  text: text().notNull(),
  osiApproved: boolean().notNull().default(false),
  notes: text(),
  createdAt: now(),
});

export const sourcePacks = pgTable(
  "source_packs",
  {
    id: uuid().primaryKey().defaultRandom(),
    slug: text().notNull().unique(),
    area: text().notNull(), // core | community | custom
    displayName: text().notNull(),
    namespace: text().notNull().unique(),
    namePrefix: text().notNull().default(""),
    upstreamUrl: text(),
    author: text(),
    copyright: text(),
    version: text().notNull(),
    distribution: jsonb().$type<Record<string, unknown>>().notNull().default({}),
    retrievedAt: date(),
    licenseId: text().notNull().references(() => licenses.id),
    notices: jsonb().$type<string[]>().notNull().default([]),
    attributionRequired: boolean().notNull().default(false),
    attributionText: text(),
    reservedFontNames: jsonb().$type<string[]>().notNull().default([]),
    permissions: jsonb().$type<Record<string, boolean>>().notNull().default({}),
    styleMapping: jsonb().$type<Record<string, unknown>>().notNull().default({}),
    styleMappingNote: text(),
    trademarkNote: text(),
    reviewStatus: text().notNull().default("pending"), // pending | approved | rejected
    reviewedBy: text(),
    reviewedAt: date(),
    reviewNote: text(),
    modificationHistory: jsonb().$type<string[]>().notNull().default([]),
    createdAt: now(),
    updatedAt: now(),
  },
);

export const styles = pgTable("styles", {
  slug: text().primaryKey(), // filled | line | rounded (extensible)
  name: text().notNull(),
  description: text().notNull(),
  sortOrder: integer().notNull().default(0),
  isCore: boolean().notNull().default(true),
});

export const categories = pgTable("categories", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull().unique(),
  name: text().notNull(),
  description: text(),
});

export const tags = pgTable("tags", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull().unique(),
});

// ------------------------------------------------------------------ concepts, designs, variants

export const concepts = pgTable("concepts", {
  id: uuid().primaryKey(),
  slug: text().notNull().unique(),
  name: text().notNull(),
  description: text(),
  createdAt: now(),
});

export const releases = pgTable("releases", {
  id: uuid().primaryKey().defaultRandom(),
  version: text().notNull().unique(),
  releaseDate: date().notNull(),
  status: text().notNull().default("draft"), // draft | approved | published | retired
  toolchain: text(),
  counts: jsonb().$type<Record<string, number>>().notNull().default({}),
  manifest: jsonb().$type<Record<string, unknown>>().notNull().default({}),
  archiveIndex: jsonb().$type<Record<string, unknown>>(),
  approvedBy: text(),
  approvedAt: timestamp({ withTimezone: true }),
  publishedAt: timestamp({ withTimezone: true }),
  createdAt: now(),
});

export const designs = pgTable(
  "designs",
  {
    id: uuid().primaryKey(),
    conceptId: uuid().notNull().references(() => concepts.id),
    sourcePackId: uuid().notNull().references(() => sourcePacks.id),
    name: text().notNull().unique(), // canonical, globally unique slug (e.g. home, tabler-home)
    localName: text().notNull(), // pack-local name (home)
    nativeName: text().notNull(), // upstream spelling (home, arrow_forward)
    namespace: text().notNull(),
    area: text().notNull(), // core | community | custom
    description: text(),
    tags: text().array().notNull().default(sql`'{}'::text[]`),
    categorySlugs: text().array().notNull().default(sql`'{}'::text[]`),
    aliasNames: text().array().notNull().default(sql`'{}'::text[]`),
    publishedStyles: text().array().notNull().default(sql`'{}'::text[]`),
    isBrand: boolean().notNull().default(false),
    // Source-specific facts, e.g. brand logos: { title, hex, sourceUrl, guidelines, licenseUrl }
    attributes: jsonb().$type<Record<string, string | null>>().notNull().default({}),
    derivedFrom: jsonb().$type<{ name: string; transform: string } | null>(),
    status: text().notNull().default("pending"), // published | pending | deprecated | rejected
    deprecatedBy: text(),
    codepoint: integer(),
    bmpCodepoint: integer(),
    licenseId: text().notNull().references(() => licenses.id),
    firstReleaseId: uuid().references(() => releases.id),
    // Search keywords (synonyms, use cases, common queries) and a plain-language context passage.
    keywords: text().array().notNull().default(sql`'{}'::text[]`),
    context: text(),
    searchNames: text().notNull().default(""),
    searchTags: text().notNull().default(""),
    // A: names and aliases. B: tags and keywords. C: description and context, stemmed (matches "running" to "run").
    // D: description and context unstemmed, so prefix queries on raw words still match.
    search: tsvector().generatedAlwaysAs(
      sql`setweight(to_tsvector('simple'::regconfig, coalesce(search_names, '')), 'A') || setweight(to_tsvector('simple'::regconfig, coalesce(search_tags, '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce(description, '') || ' ' || coalesce(context, '')), 'C') || setweight(to_tsvector('simple'::regconfig, coalesce(description, '') || ' ' || coalesce(context, '')), 'D')`,
    ),
    createdAt: now(),
    updatedAt: now(),
  },
  (t) => [
    uniqueIndex("designs_source_native_uq").on(t.sourcePackId, t.nativeName),
    index("designs_search_gin").using("gin", t.search),
    index("designs_local_trgm").using("gin", sql`${t.localName} gin_trgm_ops`),
    index("designs_name_trgm").using("gin", sql`${t.name} gin_trgm_ops`),
    index("designs_categories_gin").using("gin", t.categorySlugs),
    index("designs_aliases_gin").using("gin", t.aliasNames),
    index("designs_styles_gin").using("gin", t.publishedStyles),
    index("designs_area_status_idx").on(t.area, t.status),
    index("designs_concept_idx").on(t.conceptId),
  ],
);

export const designCategories = pgTable(
  "design_categories",
  {
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    categoryId: uuid().notNull().references(() => categories.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.designId, t.categoryId] })],
);

export const designTags = pgTable(
  "design_tags",
  {
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    tagId: uuid().notNull().references(() => tags.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.designId, t.tagId] }), index("design_tags_tag_idx").on(t.tagId)],
);

export const variants = pgTable(
  "variants",
  {
    id: uuid().primaryKey(), // immutable, stable across rebuilds
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    style: text().notNull().references(() => styles.slug),
    nativeStyle: text().notNull(),
    nativeLabel: text().notNull(),
    status: text().notNull(), // published | pending | rejected | quarantined
    reviewStatus: text().notNull().default("approved"), // approved | proposed | rejected
    route: text().notNull(), // font | svg-only | rejected
    reasons: text().array().notNull().default(sql`'{}'::text[]`),
    duplicateOfStyle: text(),
    svg: text(),
    svgSha256: text(),
    viewBox: real().array(),
    sourcePath: text().notNull(),
    sourceSha256: text().notNull(),
    outlineKey: text(),
    outlineD: text(), // font-units outline for the worker; never selected by list queries
    outlineAdvance: integer(),
    fontSupported: boolean().notNull().default(false),
    firstReleaseId: uuid().references(() => releases.id),
    updatedReleaseId: uuid().references(() => releases.id),
    createdAt: now(),
    updatedAt: now(),
  },
  (t) => [
    uniqueIndex("variants_design_style_uq").on(t.designId, t.style),
    index("variants_style_status_idx").on(t.style, t.status),
    index("variants_svg_sha_idx").on(t.svgSha256),
  ],
);

/** Global name/alias collision registry. Unique per (namespace, name). */
export const nameRegistry = pgTable(
  "name_registry",
  {
    namespace: text().notNull(),
    name: text().notNull(),
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    kind: text().notNull(), // canonical | alias | pack-local | deprecated
    createdAt: now(),
  },
  (t) => [primaryKey({ columns: [t.namespace, t.name] }), index("name_registry_design_idx").on(t.designId)],
);

export const aliases = pgTable(
  "aliases",
  {
    id: uuid().primaryKey().defaultRandom(),
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    namespace: text().notNull(),
    name: text().notNull(),
    kind: text().notNull().default("alias"), // alias | deprecated-name
    compileToFont: boolean().notNull().default(true),
    createdAt: now(),
  },
  (t) => [uniqueIndex("aliases_ns_name_uq").on(t.namespace, t.name)],
);

export const codepointAssignments = pgTable(
  "codepoint_assignments",
  {
    namespace: text().notNull(),
    subject: text().notNull(), // concept slug (core) or design name (packs)
    codepoint: integer().notNull(),
    bmpCodepoint: integer(),
    assignedAt: now(),
  },
  (t) => [
    primaryKey({ columns: [t.namespace, t.subject] }),
    uniqueIndex("codepoints_ns_cp_uq").on(t.namespace, t.codepoint),
    uniqueIndex("codepoints_ns_bmp_uq").on(t.namespace, t.bmpCodepoint),
  ],
);

// ------------------------------------------------------------------ fonts & release artifacts

export const fontBundles = pgTable(
  "font_bundles",
  {
    id: uuid().primaryKey().defaultRandom(),
    releaseId: uuid().notNull().references(() => releases.id, { onDelete: "cascade" }),
    slug: text().notNull(),
    family: text().notNull(),
    postscriptName: text().notNull(),
    sourcePackId: uuid().notNull().references(() => sourcePacks.id),
    style: text().notNull().references(() => styles.slug),
    part: integer(),
    cssClass: text().notNull(),
    glyphCount: integer().notNull(),
    keywordCount: integer().notNull(),
    files: jsonb().$type<Record<string, { name: string; bytes: number; sha256: string; storageKey?: string }>>().notNull(),
    validation: jsonb().$type<Record<string, unknown>>().notNull(),
    raster: jsonb().$type<Record<string, unknown>>(),
    createdAt: now(),
  },
  (t) => [uniqueIndex("font_bundles_release_slug_uq").on(t.releaseId, t.slug)],
);

export const glyphAssignments = pgTable(
  "glyph_assignments",
  {
    fontBundleId: uuid().notNull().references(() => fontBundles.id, { onDelete: "cascade" }),
    variantId: uuid().notNull().references(() => variants.id, { onDelete: "cascade" }),
    codepoint: integer().notNull(),
    keywords: text().array().notNull(),
  },
  (t) => [primaryKey({ columns: [t.fontBundleId, t.variantId] }), index("glyph_assignments_variant_idx").on(t.variantId)],
);

export const releaseArchives = pgTable(
  "release_archives",
  {
    id: uuid().primaryKey().defaultRandom(),
    releaseId: uuid().notNull().references(() => releases.id, { onDelete: "cascade" }),
    kind: text().notNull(),
    label: text().notNull(),
    file: text().notNull(),
    storageKey: text().notNull(),
    bytes: bigint({ mode: "number" }).notNull(),
    sha256: text().notNull(),
    meta: jsonb().$type<Record<string, unknown>>().notNull().default({}),
  },
  (t) => [uniqueIndex("release_archives_release_file_uq").on(t.releaseId, t.file)],
);

export const catalogStats = pgTable("catalog_stats", {
  id: text().primaryKey(), // "current"
  data: jsonb().$type<Record<string, unknown>>().notNull(),
  computedAt: now(),
});

// ------------------------------------------------------------------ teams, collections, kits

export const teams = pgTable("teams", {
  id: uuid().primaryKey().defaultRandom(),
  slug: text().notNull().unique(),
  name: text().notNull(),
  createdAt: now(),
});

export const memberships = pgTable(
  "memberships",
  {
    teamId: uuid().notNull().references(() => teams.id, { onDelete: "cascade" }),
    userId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    role: text().notNull().default("member"), // owner | admin | member
    createdAt: now(),
  },
  (t) => [primaryKey({ columns: [t.teamId, t.userId] })],
);

export const collections = pgTable(
  "collections",
  {
    id: uuid().primaryKey().defaultRandom(),
    ownerId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    name: text().notNull(),
    description: text(),
    isPublic: boolean().notNull().default(false),
    createdAt: now(),
    updatedAt: now(),
  },
  (t) => [index("collections_owner_idx").on(t.ownerId)],
);

export const collectionItems = pgTable(
  "collection_items",
  {
    collectionId: uuid().notNull().references(() => collections.id, { onDelete: "cascade" }),
    designId: uuid().notNull().references(() => designs.id, { onDelete: "cascade" }),
    style: text().notNull().references(() => styles.slug),
    position: integer().notNull().default(0),
    addedAt: now(),
  },
  (t) => [primaryKey({ columns: [t.collectionId, t.designId, t.style] })],
);

export const kits = pgTable(
  "kits",
  {
    id: uuid().primaryKey().defaultRandom(),
    ownerId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    teamId: uuid().references(() => teams.id, { onDelete: "set null" }),
    name: text().notNull(),
    slug: text().notNull(),
    embedId: text().notNull().unique(), // public identifier, not a secret
    pinnedReleaseId: uuid().references(() => releases.id),
    allowedDomains: text().array().notNull().default(sql`'{}'::text[]`),
    currentVersion: integer().notNull().default(0),
    createdAt: now(),
    updatedAt: now(),
  },
  (t) => [uniqueIndex("kits_owner_slug_uq").on(t.ownerId, t.slug)],
);

export const kitVersions = pgTable(
  "kit_versions",
  {
    id: uuid().primaryKey().defaultRandom(),
    kitId: uuid().notNull().references(() => kits.id, { onDelete: "cascade" }),
    version: integer().notNull(),
    selection: jsonb().$type<{ items: { designId: string; styles: string[] }[]; customIconIds: string[] }>().notNull(),
    formats: text().array().notNull(),
    contentHash: text().notNull(),
    createdBy: text().notNull().references(() => user.id),
    createdAt: now(),
  },
  (t) => [uniqueIndex("kit_versions_kit_version_uq").on(t.kitId, t.version)],
);

export const customIcons = pgTable(
  "custom_icons",
  {
    id: uuid().primaryKey().defaultRandom(),
    ownerId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    kitId: uuid().notNull().references(() => kits.id, { onDelete: "cascade" }),
    name: text().notNull(),
    style: text().notNull().default("line").references(() => styles.slug),
    status: text().notNull().default("pending"), // pending | ready | rejected (set by the worker's sanitizer)
    rawSvg: text(), // bounded upload, never rendered; cleared once processed
    svg: text(), // sanitized display SVG (worker output)
    svgSha256: text(),
    route: text(), // font | svg-only
    reasons: text().array().notNull().default(sql`'{}'::text[]`),
    outlineD: text(),
    outlineAdvance: integer(),
    codepoint: integer().notNull(), // kit namespace U+10F000+n; never reused (rows are archived, not deleted)
    archivedAt: timestamp({ withTimezone: true }),
    createdAt: now(),
  },
  (t) => [
    uniqueIndex("custom_icons_kit_name_style_uq").on(t.kitId, t.name, t.style),
    uniqueIndex("custom_icons_kit_cp_style_uq").on(t.kitId, t.codepoint, t.style),
  ],
);

// ------------------------------------------------------------------ jobs, build cache, outbox, audit

export const jobs = pgTable(
  "jobs",
  {
    id: uuid().primaryKey().defaultRandom(),
    kind: text().notNull(), // subset_build | kit_build | release_publish
    status: text().notNull().default("queued"), // queued | running | succeeded | failed | cancelled
    ownerId: text().references(() => user.id, { onDelete: "set null" }),
    scope: text().notNull().default("public"), // public | private:<userId>
    cacheKey: text(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    result: jsonb().$type<Record<string, unknown>>(),
    error: text(),
    attempts: integer().notNull().default(0),
    maxAttempts: integer().notNull().default(3),
    runAfter: timestamp({ withTimezone: true }).notNull().defaultNow(),
    lockedBy: text(),
    lockedAt: timestamp({ withTimezone: true }),
    heartbeatAt: timestamp({ withTimezone: true }),
    createdAt: now(),
    startedAt: timestamp({ withTimezone: true }),
    finishedAt: timestamp({ withTimezone: true }),
  },
  (t) => [
    index("jobs_claim_idx").on(t.status, t.runAfter),
    index("jobs_owner_idx").on(t.ownerId, t.createdAt),
    index("jobs_cache_idx").on(t.scope, t.cacheKey),
  ],
);

export const buildArtifacts = pgTable(
  "build_artifacts",
  {
    id: uuid().primaryKey().defaultRandom(),
    scope: text().notNull(), // public | private:<userId>; cache hits never cross scopes
    cacheKey: text().notNull(),
    storageKey: text().notNull(),
    fileName: text().notNull(),
    bytes: bigint({ mode: "number" }).notNull(),
    sha256: text().notNull(),
    manifest: jsonb().$type<Record<string, unknown>>().notNull(),
    jobId: uuid().references(() => jobs.id, { onDelete: "set null" }),
    createdAt: now(),
    lastUsedAt: now(),
  },
  (t) => [uniqueIndex("build_artifacts_scope_key_uq").on(t.scope, t.cacheKey)],
);

export const outbox = pgTable(
  "outbox",
  {
    id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    topic: text().notNull(),
    payload: jsonb().$type<Record<string, unknown>>().notNull(),
    createdAt: now(),
    processedAt: timestamp({ withTimezone: true }),
    attempts: integer().notNull().default(0),
    lastError: text(),
  },
  (t) => [index("outbox_pending_idx").on(t.processedAt, t.id)],
);

export const auditEvents = pgTable(
  "audit_events",
  {
    id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    actorId: text(), // user id or "system:<component>"
    action: text().notNull(),
    subjectType: text().notNull(),
    subjectId: text(),
    data: jsonb().$type<Record<string, unknown>>().notNull().default({}),
    createdAt: now(),
  },
  (t) => [index("audit_events_subject_idx").on(t.subjectType, t.subjectId), index("audit_events_created_idx").on(t.createdAt)],
);

// ------------------------------------------------------------------ entitlements & quotas

export const plans = pgTable("plans", {
  slug: text().primaryKey(), // free | pro | team (no prices here; checkout hidden until configured)
  name: text().notNull(),
  capabilities: jsonb().$type<Record<string, number | boolean>>().notNull(),
  isDefault: boolean().notNull().default(false),
});

export const userEntitlements = pgTable(
  "user_entitlements",
  {
    userId: text().notNull().references(() => user.id, { onDelete: "cascade" }),
    planSlug: text().notNull().references(() => plans.slug),
    source: text().notNull(), // manual | billing:<provider>
    startsAt: now(),
    endsAt: timestamp({ withTimezone: true }),
  },
  (t) => [primaryKey({ columns: [t.userId, t.planSlug] })],
);

export const rateLimits = pgTable(
  "rate_limits",
  {
    key: text().notNull(),
    windowStart: timestamp({ withTimezone: true }).notNull(),
    count: integer().notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.key, t.windowStart] })],
);

export const searchLog = pgTable(
  "search_metrics",
  {
    id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
    queryLength: integer().notNull(), // no query text: avoids collecting personal data
    resultCount: integer().notNull(),
    durationMs: doublePrecision().notNull(),
    createdAt: now(),
  },
  (t) => [index("search_metrics_created_idx").on(t.createdAt)],
);

/**
 * Admin metadata edits. Applied to the live catalog immediately (search, pages) and exported to
 * assets/registry/overrides.json by `typeicon-import pull-overrides`, so the next catalog build and
 * release compile them into fonts (aliases) and metadata.
 */
export const metadataOverrides = pgTable("metadata_overrides", {
  designName: text().primaryKey(),
  data: jsonb().$type<{ description?: string; tags?: string[]; categories?: string[]; aliases?: string[] }>().notNull(),
  updatedBy: text().notNull(),
  updatedAt: now(),
});
