"""TypeIcon Core icon definitions (design source for assets/core/svg).

Each icon provides:
  stroke(S)  -> list of SVG elements drawn with the shared 2px stroke. Called once
                with LINE (butt caps, miter joins, sharp polylines, 2px container
                corners) and once with ROUNDED (round caps/joins, 1.5px polyline
                fillets, 4px container corners).
  filled()   -> explicitly designed solid geometry (pathops Path). Never a fill
                toggle on the outline: silhouettes are drawn to the outer stroke
                edge and interior details are knocked out with 2px counters, or
                (for pure-stroke glyphs) drawn as heavier solid forms.

Grid: 24 x 24, live area 2..22, stroke 2. See docs/design/core-grid.md.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Callable

from geometry import (
    D, I, P, ST, U, Style, arc_d, circle_d, el_dot, el_path, poly_d, polar, rect_d,
)


@dataclass
class Icon:
    name: str
    category: str
    description: str
    tags: list[str]
    stroke: Callable[[Style], list[str]]
    filled: Callable[[], object]
    aliases: list[str] = field(default_factory=list)
    derived_from: dict | None = None


ICONS: list[Icon] = []


def icon(name, category, description, tags=(), aliases=()):
    def deco(fn):
        stroke_fn, filled_fn = fn()
        ICONS.append(Icon(name, category, description, list(tags), stroke_fn, filled_fn, list(aliases)))
        return fn
    return deco


def rotated(base: str, name: str, deg: int, description: str, tags=(), aliases=()):
    """Directional sibling generated by rotating a base design. Recorded as a
    transform-derived design so the audit never counts it as independent artwork."""
    src = next(i for i in ICONS if i.name == base)
    ICONS.append(Icon(
        name, src.category, description, list(tags), src.stroke, src.filled, list(aliases),
        derived_from={"name": base, "transform": f"rotate({deg} 12 12)", "rotate": deg},
    ))


def ring(cx, cy, r, w=2.0):
    return D(P(circle_d(cx, cy, r + w / 2)), P(circle_d(cx, cy, r - w / 2)))


def solid_outline(d, w=2.0, join="miter", miter=4.0):
    """Region covered by a closed outline when filled to its outer stroke edge."""
    return U(P(d), ST(d, w, "butt", join, miter))


# =========================================================================== navigation

@icon("home", "navigation", "A house; the start or main page.", ["house", "main", "start", "dashboard", "index"], ["house"])
def _():
    def s(S):
        return [
            el_path(poly_d([(3, 11), (12, 3), (21, 11)], r=S.r)),
            el_path(poly_d([(5, 9.3), (5, 21), (19, 21), (19, 9.3)], r=S.r)),
            el_path(poly_d([(10, 21), (10, 15), (14, 15), (14, 21)], r=S.r)),
        ]

    def f():
        roof = ST(poly_d([(3, 11), (12, 3), (21, 11)]), 2)
        body = P(poly_d([(4, 9.8), (12, 2.9), (20, 9.8), (20, 22), (4, 22)], closed=True))
        return D(U(roof, body), P(rect_d(10, 15, 4, 8)))
    return s, f


@icon("arrow-right", "arrows", "Arrow pointing right; next, forward, continue.", ["next", "forward", "continue", "proceed", "east"], ["arrow-forward"])
def _():
    def s(S):
        return [el_path("M4 12H19.5"), el_path(poly_d([(14, 6), (20, 12), (14, 18)], r=S.r))]

    def f():
        return U(P(poly_d([(12.5, 4.5), (20.5, 12), (12.5, 19.5)], closed=True)), P(rect_d(3, 10.5, 11, 3)))
    return s, f


rotated("arrow-right", "arrow-left", 180, "Arrow pointing left; back, previous.", ["back", "previous", "return", "west"], ["arrow-back"])
rotated("arrow-right", "arrow-down", 90, "Arrow pointing down.", ["down", "south", "descend"])
rotated("arrow-right", "arrow-up", 270, "Arrow pointing up.", ["up", "north", "ascend"])


@icon("arrow-right-circle", "arrows", "Right arrow inside a circle.", ["next", "forward", "go", "circle"], [])
def _():
    def s(S):
        return [
            el_path(circle_d(12, 12, 9)),
            el_path("M7.5 12H15.5"),
            el_path(poly_d([(12.25, 8.25), (16, 12), (12.25, 15.75)], r=S.r)),
        ]

    def f():
        arrow = U(ST("M7.5 12H15"), ST(poly_d([(12.25, 8.25), (16, 12), (12.25, 15.75)])))
        return D(P(circle_d(12, 12, 10)), arrow)
    return s, f


@icon("arrow", "arrows", "Pointer arrow, as used for a mouse cursor.", ["cursor", "pointer", "select", "mouse", "click"], ["cursor", "pointer"])
def _():
    pts = [(5, 3.5), (5, 19.5), (9.4, 15.6), (12.3, 21.5), (15, 20.2), (12.2, 14.4), (18, 14.4)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.66))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("chevron-right", "arrows", "Chevron pointing right; expand, next.", ["next", "expand", "disclosure", "caret"], [])
def _():
    def s(S):
        return [el_path(poly_d([(9, 5), (16, 12), (9, 19)], r=S.r))]

    def f():
        return ST(poly_d([(8.75, 5), (15.75, 12), (8.75, 19)]), 3.25)
    return s, f


rotated("chevron-right", "chevron-down", 90, "Chevron pointing down; open, expand.", ["expand", "open", "dropdown", "caret"], [])


@icon("menu", "navigation", "Three horizontal lines; navigation menu.", ["hamburger", "navigation", "lines", "options"], ["hamburger"])
def _():
    def s(S):
        return [el_path("M3 6H21"), el_path("M3 12H21"), el_path("M3 18H21")]

    def f():
        return U(*(P(rect_d(3, y - 1.5, 18, 3)) for y in (6, 12, 18)))
    return s, f


@icon("external-link", "navigation", "Box with an arrow leaving it; opens elsewhere.", ["open", "new window", "outbound", "link"], ["open-external"])
def _():
    def s(S):
        return [
            el_path(poly_d([(18, 13.5), (18, 20), (4, 20), (4, 6), (10.5, 6)], r=S.R / 2)),
            el_path("M11 13L19.5 4.5"),
            el_path(poly_d([(14, 4), (20, 4), (20, 10)], r=S.r)),
        ]

    def f():
        box = ST(poly_d([(18, 13.5), (18, 20), (4, 20), (4, 6), (10.5, 6)]), 2.75)
        return U(box, ST("M10.5 13.5L17 7", 2.75), P(poly_d([(13, 3), (21, 3), (21, 11)], closed=True)))
    return s, f



@icon("refresh", "actions", "Circular arrow; reload or sync.", ["reload", "sync", "update", "rotate", "redo"], ["reload"])
def _():
    arc = arc_d(12, 12, 8, 25, 315) + "L20.5 9.2"
    head = [(20.5, 3.5), (20.5, 9.2), (14.8, 9.2)]

    def s(S):
        return [el_path(arc), el_path(poly_d(head, r=S.r))]

    def f():
        tri = P(poly_d([(21.75, 2.25), (21.75, 10.45), (13.55, 10.45)], closed=True))
        return U(ST(arc_d(12, 12, 8, 25, 318), 2.75), tri)
    return s, f


# =========================================================================== actions

@icon("search", "actions", "Magnifying glass; search or find.", ["find", "magnify", "magnifier", "lookup", "zoom", "query"], ["magnify", "find"])
def _():
    def s(S):
        return [el_path(circle_d(10.5, 10.5, 6.5)), el_path("M15.4 15.4L21 21")]

    def f():
        return U(ring(10.5, 10.5, 6.25, 3.5), ST("M14.8 14.8L21.2 21.2", 3.5))
    return s, f


@icon("settings", "actions", "Gear; settings, preferences, configuration.", ["gear", "cog", "preferences", "options", "configuration", "setup"], ["gear", "cog"])
def _():
    def gear_pts(r0=7.4, r1=9.6, n=8, a_base=15.5, a_tip=9.5):
        pts = []
        for i in range(n):
            th = i * 360 / n - 90
            pts += [polar(12, 12, r0, th - a_base), polar(12, 12, r1, th - a_tip),
                    polar(12, 12, r1, th + a_tip), polar(12, 12, r0, th + a_base)]
        return pts

    def s(S):
        return [el_path(poly_d(gear_pts(), closed=True, r=S.r * 0.6)), el_path(circle_d(12, 12, 3))]

    def f():
        return D(solid_outline(poly_d(gear_pts(), closed=True)), P(circle_d(12, 12, 3.25)))
    return s, f


@icon("plus", "actions", "Plus sign; add or create.", ["add", "new", "create", "increase"], ["add"])
def _():
    def s(S):
        return [el_path("M12 4V20"), el_path("M4 12H20")]

    def f():
        return U(P(rect_d(10.5, 3.5, 3, 17)), P(rect_d(3.5, 10.5, 17, 3)))
    return s, f


@icon("minus", "actions", "Minus sign; remove or decrease.", ["subtract", "remove", "decrease", "less"], ["subtract"])
def _():
    def s(S):
        return [el_path("M4 12H20")]

    def f():
        return P(rect_d(3.5, 10.5, 17, 3))
    return s, f


@icon("close", "actions", "Diagonal cross; close, dismiss or cancel.", ["x", "cancel", "dismiss", "remove", "delete", "times"], ["times"])
def _():
    def s(S):
        return [el_path("M6 6L18 18"), el_path("M18 6L6 18")]

    def f():
        return U(ST("M5.5 5.5L18.5 18.5", 3.25), ST("M18.5 5.5L5.5 18.5", 3.25))
    return s, f


@icon("check", "actions", "Check mark; done, confirm, success.", ["done", "ok", "confirm", "success", "tick", "yes"], ["tick", "done"])
def _():
    def s(S):
        return [el_path(poly_d([(4, 12.5), (9, 17.5), (20, 6.5)], r=S.r))]

    def f():
        return ST(poly_d([(3.5, 12.5), (9, 18), (20.5, 6.5)]), 3.25)
    return s, f


@icon("edit", "actions", "Pencil; edit or write.", ["pencil", "write", "modify", "compose", "change"], [])
def _():
    body = [(16.5, 3.5), (20.5, 7.5), (8, 20), (4, 20), (4, 16)]

    def s(S):
        return [el_path(poly_d(body, closed=True, r=S.r * 0.66)), el_path("M13.5 6.5L17.5 10.5")]

    def f():
        return D(solid_outline(poly_d(body, closed=True)), ST("M13.25 6.25L17.75 10.75", 1.75))
    return s, f


@icon("trash", "actions", "Waste bin; delete.", ["delete", "bin", "remove", "garbage", "rubbish", "discard"], ["delete", "bin"])
def _():
    def s(S):
        return [
            el_path("M3 6H21"),
            el_path(poly_d([(9, 6), (9, 3), (15, 3), (15, 6)], r=S.r * 0.66)),
            el_path(poly_d([(5.5, 6), (6.5, 21), (17.5, 21), (18.5, 6)], r=S.r)),
            el_path("M10 10.5V16.5"),
            el_path("M14 10.5V16.5"),
        ]

    def f():
        lid = U(P(rect_d(2.5, 4.5, 19, 3)), ST(poly_d([(9, 6), (9, 3), (15, 3), (15, 6)]), 2))
        body = P(poly_d([(4.5, 9), (19.5, 9), (18.5, 22), (5.5, 22)], closed=True))
        slots = U(P(rect_d(9.1, 11, 1.8, 7.5, 0.9)), P(rect_d(13.1, 11, 1.8, 7.5, 0.9)))
        return U(lid, D(body, slots))
    return s, f


@icon("download", "actions", "Arrow into a tray; download or save.", ["save", "import", "get", "arrow", "fetch"], ["save-down"])
def _():
    def s(S):
        return [
            el_path("M12 3V15"),
            el_path(poly_d([(7, 10), (12, 15), (17, 10)], r=S.r)),
            el_path(poly_d([(3, 15), (3, 21), (21, 21), (21, 15)], r=S.r)),
        ]

    def f():
        arrow = U(P(rect_d(10.5, 2.5, 3, 9)), P(poly_d([(6, 10), (18, 10), (12, 16.5)], closed=True)))
        tray = D(P(rect_d(2, 14, 20, 8, 2)), P(rect_d(5, 13, 14, 4)))
        return U(arrow, tray)
    return s, f


@icon("upload", "actions", "Arrow out of a tray; upload or send.", ["export", "send", "share", "arrow", "publish"], [])
def _():
    def s(S):
        return [
            el_path("M12 16V4"),
            el_path(poly_d([(7, 9), (12, 4), (17, 9)], r=S.r)),
            el_path(poly_d([(3, 15), (3, 21), (21, 21), (21, 15)], r=S.r)),
        ]

    def f():
        arrow = U(P(rect_d(10.5, 8, 3, 9)), P(poly_d([(6, 9.5), (12, 3), (18, 9.5)], closed=True)))
        tray = D(P(rect_d(2, 14, 20, 8, 2)), P(rect_d(5, 13, 14, 4)))
        return U(arrow, tray)
    return s, f


@icon("share", "actions", "Box with an upward arrow; share.", ["send", "export", "social", "forward"], [])
def _():
    def s(S):
        return [
            el_path(poly_d([(8.5, 9), (5, 9), (5, 21), (19, 21), (19, 9), (15.5, 9)], r=S.R / 2)),
            el_path("M12 3.5V15"),
            el_path(poly_d([(8, 7), (12, 3), (16, 7)], r=S.r)),
        ]

    def f():
        box = ST(poly_d([(8.5, 9), (5, 9), (5, 21), (19, 21), (19, 9), (15.5, 9)]), 2.75)
        return U(box, P(rect_d(10.625, 6, 2.75, 9.5)), P(poly_d([(6.5, 8.25), (12, 2.5), (17.5, 8.25)], closed=True)))
    return s, f



@icon("link", "actions", "Two chain links; hyperlink.", ["chain", "url", "hyperlink", "attach", "connect"], ["chain"])
def _():
    a = "M10 13.5A4 4 0 0 0 15.66 13.9L18.5 11.07A4 4 0 0 0 12.84 5.41L11.4 6.85"
    b = "M14 10.5A4 4 0 0 0 8.34 10.1L5.5 12.93A4 4 0 0 0 11.16 18.59L12.6 17.15"

    def s(S):
        return [el_path(a), el_path(b)]

    def f():
        return U(ST(a, 2.75, "butt"), ST(b, 2.75, "butt"))
    return s, f


@icon("copy", "actions", "Two overlapping sheets; duplicate or copy.", ["duplicate", "clone", "clipboard"], ["duplicate"])
def _():
    def s(S):
        return [
            el_path(rect_d(9, 9, 12, 12, S.R * 0.75)),
            el_path(poly_d([(15, 5), (15, 3), (3, 3), (3, 15), (5, 15)], r=S.R * 0.75)),
        ]

    def f():
        back = D(P(rect_d(2, 2, 14, 14, 2)), P(rect_d(7, 7, 16, 16, 3)))
        return U(back, P(rect_d(8, 8, 14, 14, 2)))
    return s, f


@icon("filter", "actions", "Funnel; filter or sort results.", ["funnel", "sort", "refine", "narrow"], ["funnel"])
def _():
    pts = [(3, 4), (21, 4), (14, 12.5), (14, 20), (10, 18), (10, 12.5)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.66))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


# =========================================================================== status

@icon("check-circle", "status", "Check mark inside a circle; success.", ["success", "done", "complete", "verified", "ok"], [])
def _():
    tick = [(8, 12.25), (11, 15.25), (16.25, 9)]

    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path(poly_d(tick, r=S.r))]

    def f():
        return D(P(circle_d(12, 12, 10)), ST(poly_d(tick), 2))
    return s, f


@icon("close-circle", "status", "Cross inside a circle; error or clear.", ["error", "cancel", "clear", "failed", "remove"], ["x-circle"])
def _():
    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path("M9 9L15 15"), el_path("M15 9L9 15")]

    def f():
        return D(P(circle_d(12, 12, 10)), ST("M9 9L15 15"), ST("M15 9L9 15"))
    return s, f


@icon("plus-circle", "status", "Plus inside a circle; add.", ["add", "create", "new"], ["add-circle"])
def _():
    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path("M12 7.5V16.5"), el_path("M7.5 12H16.5")]

    def f():
        return D(P(circle_d(12, 12, 10)), ST("M12 7.5V16.5"), ST("M7.5 12H16.5"))
    return s, f


@icon("info", "status", "Letter i in a circle; information.", ["information", "about", "details", "help", "tooltip"], ["information"])
def _():
    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path("M12 11V16.5"), el_dot(12, 7.75, 1.25)]

    def f():
        return D(P(circle_d(12, 12, 10)), P(rect_d(11, 10.5, 2, 6.5)), P(circle_d(12, 7.6, 1.3)))
    return s, f


@icon("warning", "status", "Exclamation in a triangle; warning or caution.", ["alert", "caution", "danger", "attention", "exclamation"], ["alert"])
def _():
    tri = [(12, 4), (21.5, 20), (2.5, 20)]

    def s(S):
        return [el_path(poly_d(tri, closed=True, r=S.r * 1.3)), el_path("M12 9.5V14"), el_dot(12, 16.75, 1.25)]

    def f():
        body = solid_outline(poly_d([(12, 3.6), (21.4, 19.6), (2.6, 19.6)], closed=True), join="miter")
        return D(body, P(rect_d(11, 9, 2, 5.5)), P(circle_d(12, 16.75, 1.3)))
    return s, f


@icon("help", "status", "Question mark in a circle; help.", ["question", "support", "faq", "unknown"], ["question"])
def _():
    q = "M9.25 9.5A2.85 2.85 0 1 1 13.2 12.1C12.4 12.5 12 13 12 14"

    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path(q), el_dot(12, 17, 1.25)]

    def f():
        return D(P(circle_d(12, 12, 10)), ST(q, 2), P(rect_d(11, 13.4, 2, 1.2)), P(circle_d(12, 17, 1.3)))
    return s, f


# =========================================================================== objects

@icon("user", "people", "Head and shoulders; a person or account.", ["person", "account", "profile", "avatar", "member"], ["person", "account"])
def _():
    def s(S):
        return [el_path(circle_d(12, 7.5, 3.5)), el_path("M5 21V20A6 6 0 0 1 11 14H13A6 6 0 0 1 19 20V21")]

    def f():
        return U(P(circle_d(12, 7.5, 4.5)), P("M4 22V20.5A7 7 0 0 1 11 13.5H13A7 7 0 0 1 20 20.5V22Z"))
    return s, f


@icon("heart", "social", "Heart; like, favourite, love.", ["like", "love", "favorite", "favourite", "health"], ["like"])
def _():
    d = "M12 20L4.4 12.6A4.6 4.6 0 0 1 11 6.3L12 7.3L13 6.3A4.6 4.6 0 0 1 19.6 12.6Z"
    # Rounded softens the bottom point and the top notch; Line keeps them sharp.
    d_round = "M10.6 18.6L4.4 12.6A4.6 4.6 0 0 1 11 6.3L11.3 6.6Q12 7.3 12.7 6.6L13 6.3A4.6 4.6 0 0 1 19.6 12.6L13.4 18.6Q12 20 10.6 18.6Z"

    def s(S):
        return [el_path(d if S.name == "line" else d_round)]

    def f():
        return solid_outline(d, join="miter")
    return s, f


@icon("star", "social", "Five-pointed star; favourite or rating.", ["favorite", "favourite", "rating", "bookmark", "important"], ["favorite"])
def _():
    pts = []
    for i in range(10):
        r = 9.5 if i % 2 == 0 else 4.1
        pts.append(polar(12, 12.8, r, -90 + i * 36))

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.2))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("bell", "communication", "Bell; notifications or alerts.", ["notification", "alert", "alarm", "reminder", "ring"], ["notification"])
def _():
    body = "M6 16.5V10.5A6 6 0 0 1 18 10.5V16.5L19.5 18.5H4.5Z"

    def s(S):
        return [el_path(body), el_path("M10 21H14")]

    def f():
        return U(solid_outline(body), P("M9.75 20.5H14.25A2.25 2.25 0 0 1 9.75 20.5Z"))
    return s, f


@icon("mail", "communication", "Envelope; email or message.", ["email", "envelope", "message", "inbox", "letter"], ["email", "envelope"])
def _():
    def s(S):
        return [el_path(rect_d(3, 5, 18, 14, S.R * 0.5)), el_path(poly_d([(3.5, 6.5), (12, 13), (20.5, 6.5)], r=S.r))]

    def f():
        return D(P(rect_d(2, 4, 20, 16, 2)), ST(poly_d([(2.5, 6.5), (12, 13.75), (21.5, 6.5)]), 1.75))
    return s, f


@icon("chat", "communication", "Speech bubble; chat or comment.", ["message", "comment", "conversation", "talk", "bubble"], ["comment", "message"])
def _():
    pts = [(4, 4.5), (20, 4.5), (20, 16), (11, 16), (6.5, 20.5), (6.5, 16), (4, 16)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 1.3))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("phone", "communication", "Telephone handset; call.", ["call", "telephone", "contact", "dial"], ["call"])
def _():
    d = ("M5.2 3.5H8.6L10.4 8L8.1 9.5A11 11 0 0 0 14.5 15.9L16 13.6L20.5 15.4V18.8"
         "A1.7 1.7 0 0 1 18.8 20.5A15.5 15.5 0 0 1 3.5 5.2A1.7 1.7 0 0 1 5.2 3.5Z")
    # Line: square handset ends. Rounded: rounded ends.
    d_line = "M3.5 3.5H8.6L10.4 8L8.1 9.5A11 11 0 0 0 14.5 15.9L16 13.6L20.5 15.4V20.5H19A15.5 15.5 0 0 1 3.5 5Z"

    def s(S):
        return [el_path(d_line if S.name == "line" else d)]

    def f():
        return solid_outline(d)
    return s, f


@icon("lock", "security", "Closed padlock; locked or secure.", ["secure", "private", "password", "protected", "closed"], ["locked"])
def _():
    def s(S):
        return [
            el_path("M8 11V7.5A4 4 0 0 1 16 7.5V11"),
            el_path(rect_d(5, 11, 14, 10, S.R * 0.5)),
            el_path("M12 14.5V17.5"),
        ]

    def f():
        body = D(P(rect_d(4, 10, 16, 12, 2)), P(rect_d(11, 13.75, 2, 4.5, 1)))
        return U(ST("M8 11V7.5A4 4 0 0 1 16 7.5V11", 2.25), body)
    return s, f


@icon("unlock", "security", "Open padlock; unlocked.", ["open", "unlocked", "public", "unsecure"], ["unlocked"])
def _():
    shackle = "M8 11V7.5A4 4 0 0 1 15.75 6.1"

    def s(S):
        return [el_path(shackle), el_path(rect_d(5, 11, 14, 10, S.R * 0.5)), el_path("M12 14.5V17.5")]

    def f():
        body = D(P(rect_d(4, 10, 16, 12, 2)), P(rect_d(11, 13.75, 2, 4.5, 1)))
        return U(ST(shackle, 2.25), body)
    return s, f


@icon("key", "security", "Key; password, access or credentials.", ["password", "access", "credentials", "unlock", "auth"], [])
def _():
    def s(S):
        return [
            el_path(circle_d(7.5, 16.5, 4)),
            el_path("M10.3 13.7L20 4"),
            el_path("M17 7L19.5 9.5"),
            el_path("M14.5 9.5L16.5 11.5"),
        ]

    def f():
        head = D(P(circle_d(7.5, 16.5, 5.25)), P(circle_d(7.5, 16.5, 1.75)))
        return U(head, ST("M10 14L20.5 3.5", 2.75), ST("M16.8 6.8L19.6 9.6", 2.75), ST("M14.2 9.4L16.6 11.8", 2.75))
    return s, f


@icon("shield", "security", "Shield; protection or security.", ["security", "protection", "safe", "guard", "defense"], [])
def _():
    d = "M12 2.5L20 5.5V11C20 16 16.6 19.8 12 21.5C7.4 19.8 4 16 4 11V5.5Z"
    # Rounded fillets the three top corners.
    d_round = ("M10.95 2.9L5.05 5.1Q4 5.5 4 6.6V11C4 16 7.4 19.8 12 21.5C16.6 19.8 20 16 20 11V6.6"
               "Q20 5.5 18.95 5.1L13.05 2.9Q12 2.5 10.95 2.9Z")

    def s(S):
        return [el_path(d if S.name == "line" else d_round)]

    def f():
        return solid_outline(d)
    return s, f


@icon("calendar", "time", "Calendar page; dates and events.", ["date", "schedule", "event", "month", "day", "planner"], ["date"])
def _():
    def s(S):
        return [
            el_path(rect_d(3, 5, 18, 16, S.R * 0.75)),
            el_path("M3 10H21"),
            el_path("M8 3V7"),
            el_path("M16 3V7"),
        ]

    def f():
        head = D(P(rect_d(2, 4, 20, 5.25, 2)), P(rect_d(6, 2, 4, 5.5)), P(rect_d(14, 2, 4, 5.5)))
        head = U(head, P(rect_d(7, 2, 2, 4.5)), P(rect_d(15, 2, 2, 4.5)))
        body = P(rect_d(2, 11, 20, 11, 2))
        return U(head, body, P(rect_d(2, 8, 20, 1.25)))
    return s, f


@icon("clock", "time", "Clock face; time or history.", ["time", "history", "recent", "hour", "watch", "schedule"], ["time"])
def _():
    hands = [(12, 7), (12, 12), (15.5, 14)]

    def s(S):
        return [el_path(circle_d(12, 12, 9)), el_path(poly_d(hands, r=S.r * 0.5))]

    def f():
        return D(P(circle_d(12, 12, 10)), ST(poly_d(hands), 2))
    return s, f


@icon("bookmark", "objects", "Ribbon bookmark; save for later.", ["save", "favorite", "read later", "ribbon"], [])
def _():
    pts = [(6, 3), (18, 3), (18, 21), (12, 16.5), (6, 21)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("tag", "objects", "Price tag; label or category.", ["label", "price", "category", "badge", "sale"], ["label"])
def _():
    pts = [(3, 3), (11, 3), (21, 13), (13, 21), (3, 11)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.8)), el_dot(7.5, 7.5, 1.5)]

    def f():
        return D(solid_outline(poly_d(pts, closed=True)), P(circle_d(7.5, 7.5, 1.6)))
    return s, f


@icon("folder", "files", "Folder; a directory or collection.", ["directory", "collection", "files", "archive"], ["directory"])
def _():
    pts = [(3, 5), (9.5, 5), (11.5, 7.5), (21, 7.5), (21, 20), (3, 20)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("file", "files", "Document page with folded corner.", ["document", "page", "paper", "sheet"], ["document"])
def _():
    pts = [(5, 2.5), (14, 2.5), (19, 7.5), (19, 21.5), (5, 21.5)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r)), el_path(poly_d([(14, 2.5), (14, 7.5), (19, 7.5)], r=S.r * 0.5))]

    def f():
        page = solid_outline(poly_d(pts, closed=True))
        return D(page, ST(poly_d([(13.6, 1.5), (13.6, 7.9), (20, 7.9)]), 1.75))
    return s, f


@icon("image", "media", "Framed picture with mountains and sun.", ["picture", "photo", "gallery", "landscape"], ["picture", "photo"])
def _():
    ridge = [(3, 17), (9, 11), (14, 16), (16.5, 13.5), (21, 18)]

    def s(S):
        return [el_path(rect_d(3, 3, 18, 18, S.R * 0.75)), el_path(poly_d(ridge, r=S.r)), el_path(circle_d(15.5, 8.5, 1.75))]

    def f():
        frame = P(rect_d(2, 2, 20, 20, 2))
        return D(frame, ST(poly_d([(1, 16.5), (9, 8.8), (14, 13.8), (16.5, 11.3), (23, 17.6)]), 1.75),
                 P(circle_d(15.5, 7.25, 2)))
    return s, f


@icon("camera", "media", "Camera; photo capture.", ["photo", "capture", "snapshot", "picture"], [])
def _():
    pts = [(3, 7), (7.5, 7), (9, 4.5), (15, 4.5), (16.5, 7), (21, 7), (21, 20), (3, 20)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r)), el_path(circle_d(12, 13, 3.5))]

    def f():
        return D(solid_outline(poly_d(pts, closed=True)), ring(12, 13, 3.75, 1.75))
    return s, f


@icon("cart", "commerce", "Shopping cart.", ["shopping", "basket", "buy", "checkout", "store"], ["shopping-cart"])
def _():
    basket = [(2, 3.5), (5, 3.5), (7.5, 15), (19, 15), (21, 7), (5.9, 7)]

    def s(S):
        return [el_path(poly_d(basket, r=S.r)), el_path(circle_d(9, 19.5, 1.5)), el_path(circle_d(18, 19.5, 1.5))]

    def f():
        solid = P(poly_d([(5.9, 6), (22.3, 6), (19.8, 16), (6.8, 16)], closed=True))
        handle = ST(poly_d([(2, 3.5), (5, 3.5), (7.5, 15)]), 2)
        return U(solid, handle, P(circle_d(9, 19.5, 2.25)), P(circle_d(18, 19.5, 2.25)))
    return s, f


@icon("map-pin", "places", "Location pin; place on a map.", ["location", "place", "marker", "address", "gps"], ["location", "marker"])
def _():
    d = "M12 21.5C12 21.5 5 14.5 5 9.5A7 7 0 0 1 19 9.5C19 14.5 12 21.5 12 21.5Z"
    # Line: sharp tip. Rounded: rounded tip.
    d_round = "M10.9 20.4C8.6 17.9 5 13.4 5 9.5A7 7 0 0 1 19 9.5C19 13.4 15.4 17.9 13.1 20.4Q12 21.6 10.9 20.4Z"

    def s(S):
        return [el_path(d if S.name == "line" else d_round), el_path(circle_d(12, 9.5, 2.5))]

    def f():
        return D(solid_outline(d), P(circle_d(12, 9.5, 2.75)))
    return s, f


@icon("flag", "objects", "Flag on a pole; report or milestone.", ["report", "milestone", "mark", "country"], [])
def _():
    cloth = [(5, 4), (19, 4), (16, 8.5), (19, 13), (5, 13)]

    def s(S):
        return [el_path("M5 22V3"), el_path(poly_d(cloth, closed=True, r=S.r * 0.66))]

    def f():
        return U(P(rect_d(4, 2.5, 2.25, 20)), solid_outline(poly_d(cloth, closed=True)))
    return s, f


@icon("bolt", "objects", "Lightning bolt; power, energy or fast.", ["lightning", "flash", "power", "energy", "electric", "fast"], ["lightning", "flash"])
def _():
    pts = [(13, 2.5), (4.5, 13.5), (11, 13.5), (10, 21.5), (19.5, 10), (13, 10)]

    def s(S):
        # Acute corners: miter limit 2 bevels the spikes so they stay inside the live area.
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.5), stroke_miterlimit="2")]

    def f():
        return solid_outline(poly_d(pts, closed=True), miter=2.0)
    return s, f


@icon("eye", "actions", "Eye; view or visibility.", ["view", "visible", "show", "preview", "watch", "look"], ["view", "visible"])
def _():
    d = "M2 12C4.5 7 8 5 12 5C16 5 19.5 7 22 12C19.5 17 16 19 12 19C8 19 4.5 17 2 12Z"
    # Line: pointed almond. Rounded: blunt, rounded tips.
    d_round = ("M2.7 11.2C5 7.2 8.3 5 12 5C15.7 5 19 7.2 21.3 11.2Q21.8 12 21.3 12.8"
               "C19 16.8 15.7 19 12 19C8.3 19 5 16.8 2.7 12.8Q2.2 12 2.7 11.2Z")

    def s(S):
        return [el_path(d if S.name == "line" else d_round), el_path(circle_d(12, 12, 3))]

    def f():
        return U(D(solid_outline(d), P(circle_d(12, 12, 4.5))), P(circle_d(12, 12, 2.75)))
    return s, f


@icon("sun", "weather", "Sun with rays; light mode or daytime.", ["light", "day", "brightness", "weather", "sunny"], ["light-mode"])
def _():
    def rays(r0, r1):
        return ["M" + f"{a[0]:.3f} {a[1]:.3f}L{b[0]:.3f} {b[1]:.3f}"
                for a, b in ((polar(12, 12, r0, t), polar(12, 12, r1, t)) for t in range(0, 360, 45))]

    def s(S):
        return [el_path(circle_d(12, 12, 4))] + [el_path(d) for d in rays(7.25, 9.75)]

    def f():
        return U(P(circle_d(12, 12, 5.25)), *(ST(d, 2.5) for d in rays(7.5, 10.25)))
    return s, f


@icon("moon", "weather", "Crescent moon; dark mode or night.", ["dark", "night", "sleep", "dark mode"], ["dark-mode", "night"])
def _():
    d = "M20.5 14.5A8.5 8.5 0 1 1 9.5 3.5A7 7 0 0 0 20.5 14.5Z"

    def s(S):
        return [el_path(d)]

    def f():
        return solid_outline(d)
    return s, f


@icon("cloud", "weather", "Cloud; cloud storage or weather.", ["weather", "storage", "sky", "online"], [])
def _():
    d = "M7 19H17.5A4.5 4.5 0 0 0 18 10.03A6 6 0 0 0 6.34 9.1A5 5 0 0 0 7 19Z"
    # Line: flat base meeting the lobes at crisp corners. Rounded: lobes flow into the base.
    d_line = "M4.5 19H19.5A3.8 3.8 0 0 0 18 11.7A6 6 0 0 0 6.5 10A4.7 4.7 0 0 0 4.5 19Z"

    def s(S):
        return [el_path(d_line if S.name == "line" else d)]

    def f():
        return solid_outline(d)
    return s, f


@icon("wifi", "devices", "Wireless signal arcs.", ["wireless", "internet", "network", "signal", "connection"], ["wireless"])
def _():
    arcs = [arc_d(12, 20.5, rr, 225, 315) for rr in (5.5, 10, 14.5)]

    def s(S):
        return [el_path(arcs[0]), el_path(arcs[1]), el_path(arcs[2]), el_dot(12, 19.25, 1.25)]

    def f():
        fan = P("M12 20.5L" + f"{polar(12, 20.5, 15.5, 225)[0]:.3f} {polar(12, 20.5, 15.5, 225)[1]:.3f}"
                + arc_d(12, 20.5, 15.5, 225, 315)[arc_d(12, 20.5, 15.5, 225, 315).index('A'):] + "Z")
        gaps = U(*(ST(arc_d(12, 20.5, rr, 200, 340), 1.75) for rr in (6.75, 11.25)))
        return D(fan, gaps)
    return s, f


@icon("battery", "devices", "Battery; power level.", ["power", "charge", "energy", "level"], [])
def _():
    def s(S):
        return [el_path(rect_d(2, 7, 17, 10, S.R * 0.5)), el_path("M21.5 10.5V13.5"), el_path(rect_d(5, 10, 6, 4, 0.5), fill="currentColor", stroke="none")]

    def f():
        body = D(P(rect_d(1, 6, 19, 12, 2)), P(rect_d(12.5, 8.5, 5, 7, 0.5)))
        return U(body, P(rect_d(20.5, 9.5, 2.5, 5, 1)))
    return s, f


@icon("mic", "media", "Microphone; record or voice input.", ["microphone", "record", "voice", "audio", "speak"], ["microphone"])
def _():
    def s(S):
        return [el_path(rect_d(9, 2.5, 6, 11.5, 3)), el_path("M5 11A7 7 0 0 0 19 11"), el_path("M12 18V21.5")]

    def f():
        return U(P(rect_d(8, 1.5, 8, 13.5, 4)), ST("M5 11A7 7 0 0 0 19 11", 2), P(rect_d(10.75, 17, 2.5, 5.5)))
    return s, f


@icon("volume", "media", "Speaker with sound waves; audio volume.", ["sound", "audio", "speaker", "loud", "unmute"], ["sound", "speaker"])
def _():
    spk = [(4, 9), (8, 9), (13, 4.5), (13, 19.5), (8, 15), (4, 15)]
    w1, w2 = "M16.5 8.5A5 5 0 0 1 16.5 15.5", "M19 6A8.5 8.5 0 0 1 19 18"

    def s(S):
        return [el_path(poly_d(spk, closed=True, r=S.r * 0.66)), el_path(w1), el_path(w2)]

    def f():
        return U(solid_outline(poly_d(spk, closed=True)), ST(w1, 2.25), ST(w2, 2.25))
    return s, f


@icon("play", "media", "Play triangle; start playback.", ["start", "run", "video", "media", "resume"], ["start"])
def _():
    pts = [(6.5, 3.5), (20, 12), (6.5, 20.5)]

    def s(S):
        return [el_path(poly_d(pts, closed=True, r=S.r * 0.5))]

    def f():
        return solid_outline(poly_d(pts, closed=True))
    return s, f


@icon("pause", "media", "Two vertical bars; pause playback.", ["hold", "media", "break", "stop"], [])
def _():
    def s(S):
        return [el_path(rect_d(6, 4, 4, 16, S.R * 0.25)), el_path(rect_d(14, 4, 4, 16, S.R * 0.25))]

    def f():
        return U(P(rect_d(5, 3, 6, 18, 1)), P(rect_d(13, 3, 6, 18, 1)))
    return s, f


@icon("stop", "media", "Square; stop playback.", ["end", "halt", "media", "square"], [])
def _():
    def s(S):
        return [el_path(rect_d(5, 5, 14, 14, S.R * 0.5))]

    def f():
        return P(rect_d(4, 4, 16, 16, 1.5))
    return s, f


@icon("grid", "layout", "Four squares; grid layout or apps.", ["layout", "apps", "tiles", "dashboard", "gallery"], ["apps"])
def _():
    cells = [(3, 3), (14, 3), (3, 14), (14, 14)]

    def s(S):
        return [el_path(rect_d(x, y, 7, 7, S.R * 0.5)) for x, y in cells]

    def f():
        return U(*(P(rect_d(x - 1, y - 1, 9, 9, 1.5)) for x, y in cells))
    return s, f


@icon("list", "layout", "Bulleted list.", ["bullets", "items", "todo", "rows", "menu"], ["bullets"])
def _():
    def s(S):
        out = []
        for y in (6, 12, 18):
            out.append(el_path(f"M9 {y}H21"))
            out.append(el_dot(4.5, y, 1.25))
        return out

    def f():
        return U(*(U(P(rect_d(8.5, y - 1.5, 13, 3)), P(rect_d(2.75, y - 1.75, 3.5, 3.5, 0.5))) for y in (6, 12, 18)))
    return s, f


@icon("chart-bar", "data", "Vertical bars; statistics or analytics.", ["chart", "graph", "statistics", "analytics", "report", "data"], ["bar-chart"])
def _():
    bars = [(6, 13), (12, 5), (18, 9)]

    def s(S):
        return [el_path(f"M{x} 20V{y}") for x, y in bars]

    def f():
        return U(*(P(rect_d(x - 2, y - 1, 4, 22 - y, 0.75)) for x, y in bars))
    return s, f


@icon("smartphone", "devices", "Mobile phone device.", ["mobile", "device", "cellphone", "iphone", "android"], ["mobile"])
def _():
    def s(S):
        return [el_path(rect_d(6, 2.5, 12, 19, S.R * 0.75)), el_path("M10.5 18.5H13.5")]

    def f():
        return D(P(rect_d(5, 1.5, 14, 21, 2.5)), P(rect_d(10, 17.5, 4, 2, 1)))
    return s, f
